- hosts: localhost
  gather_facts: false
  connection: local 

  tasks:
  - name: droplet activity
    digital_ocean_droplet:
      oauth_token: "{{ token }}"
      state: "{{ state }}"
      name: ontapselect
      size: 2gb
      region: AMS3
      image: centos-7-x64
      ssh_keys: 25622611
      unique_name: yes
      wait_timeout: 600
    register: my_droplet

  - debug:
      msg: "Droplet IP is {{ my_droplet.data.ip_address }}"
    when: state == 'present'

  - name: testing connection
    command: ssh -l root -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null "{{ my_droplet.data.ip_address }}" uptime
    when: state == 'present'

  - name: add host to inventory
    add_host:
      hostname: "{{ my_droplet.data.ip_address }}"
      ansible_user: root
      #ansible_extra_args: '-oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null'
      groups: ontapselect
    when: state == 'present'

- hosts: [ontapselect]
  gather_facts: false

  vars:
    host_key_checking: false

  tasks:

  - name: yum update
    yum:
      name: '*'
      state: latest
    when: state == 'present'

  - name: yum install virt
    yum: 
      name: qemu-kvm,libvirt,libvirt-python,libguestfs-tools,virt-install
      state: latest
    when: state == 'present'

  - name: enable virt service
    service:
      name: libvirtd 
      enabled: yes 
    when: state == 'present'
    
  - name: reboot 
    reboot: 
      reboot_timeout: 3600
    when: state == 'present'


